DELETE FROM `ev_aprvvend` WHERE 1;
DELETE FROM `ev_jobasmbl` WHERE 1;
DELETE FROM `ev_jobhead` WHERE 1;
DELETE FROM `ev_jobmtl` WHERE 1;
DELETE FROM `ev_part` WHERE 1;
DELETE FROM `ev_partbin` WHERE 1;
DELETE FROM `ev_partdtl` WHERE 1;
DELETE FROM `ev_partmtl` WHERE 1;
DELETE FROM `ev_partopr` WHERE 1;
DELETE FROM `ev_partplant` WHERE 1;
DELETE FROM `ev_partrev` WHERE 1;
DELETE FROM `ev_plantwhse` WHERE 1;
DELETE FROM `ev_podetail` WHERE 1;
DELETE FROM `ev_poheader` WHERE 1;
DELETE FROM `ev_rcvdtl` WHERE 1;
DELETE FROM `ev_vendor` WHERE 1;

TRUNCATE TABLE `ev_aprvvend`;
TRUNCATE TABLE `ev_jobasmbl`;
TRUNCATE TABLE `ev_jobhead`;
TRUNCATE TABLE `ev_jobmtl`;
TRUNCATE TABLE `ev_part`;
TRUNCATE TABLE `ev_partbin`;
TRUNCATE TABLE `ev_partdtl`;
TRUNCATE TABLE `ev_partmtl`;
TRUNCATE TABLE `ev_partopr`;
TRUNCATE TABLE `ev_partplant`;
TRUNCATE TABLE `ev_partrev`;
TRUNCATE TABLE `ev_plantwhse`;
TRUNCATE TABLE `ev_podetail`;
TRUNCATE TABLE `ev_poheader`;
TRUNCATE TABLE `ev_rcvdtl`;
TRUNCATE TABLE `ev_vendor`;
